/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.sql.*;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Gai
 */
public class FuncionarioView extends javax.swing.JFrame {

    //Gerador chama a class tabela e dá um nome
    //..........................................
    public static int index;

    //Chama a class FuncionarioWrite e dá um nome
    //........................................
    String Funcao = "";
    private String Sexo;

    public void LoadTable() {
        //Modelo recebe a criação de tabelas

        //..................................
        //Seta o conteúdo de modelo na tabela local
        //.........................................
        //Define as larguras de cada posição
        //..................................
    }

    public FuncionarioView() {
        initComponents();
        setFocusLostBehavior();

        this.setResizable(false);

        if (!BD.getConnection()) {
            JOptionPane.showMessageDialog(null, "Falha na conexão, o sistema será fechado");
            System.exit(0);

        }

        LoadTable();

        setLocationRelativeTo(null);

        //Modo "Excluir" desativa a maioria dos botões
        //Chama a função do modoDep
        //.........................     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jNovo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jExcluir = new javax.swing.JButton();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jLimpar = new javax.swing.JButton();
        jEdit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jCPF = new javax.swing.JFormattedTextField();
        jOBS = new javax.swing.JTextField();
        jCelular = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCadastrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jDepartamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDataEntrada = new javax.swing.JFormattedTextField();
        jConsultar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jDataNascimento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jSenha = new javax.swing.JTextField();
        jFuncao = new javax.swing.JComboBox<>();
        jSalario = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("FUNÇÃO");

        jNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNovo.setText("Novo");
        jNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("DATA DE NASCIMENTO");

        jExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jExcluir.setText("Excluir");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrMasculino);
        jrMasculino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrMasculino.setText("Masculino");
        jrMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMasculinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrFeminino);
        jrFeminino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrFeminino.setText("Feminino");
        jrFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFemininoActionPerformed(evt);
            }
        });

        jLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLimpar.setText("Limpar campo");
        jLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimparActionPerformed(evt);
            }
        });

        jEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEdit.setText("Editar");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("OBSERVAÇÃO");

        try {
            jCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPFActionPerformed(evt);
            }
        });

        jOBS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            jCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCelularActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("CELULAR");

        jEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("SALÁRIO");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("E-MAIL");

        jNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNome.setToolTipText("");
        jNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Quartz", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 188, 227));
        jLabel1.setText("Cadastro de funcionário");

        jCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCadastrar.setText("Cadastrar");
        jCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("DATA DE ENTRADA");
        jLabel10.setToolTipText("");

        jDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepartamentoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("NOME");
        jLabel2.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("DEPARTAMENTO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("CPF");

        try {
            jDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jDataEntrada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jConsultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jConsultar.setText("Consultar");
        jConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarActionPerformed(evt);
            }
        });

        jCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCancelar.setText("Cancelar");

        try {
            jDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("SENHA");

        jSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jFuncao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendas", "Gerente Comercial", "Gestor Comercial", "Faturamento", "Expedição", "Ti", "" }));
        jFuncao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFuncaoFocusGained(evt);
            }
        });
        jFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFuncaoActionPerformed(evt);
            }
        });

        try {
            jSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("$######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDataNascimento)
                            .addComponent(jEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSalario))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCelular)
                            .addComponent(jDataEntrada)
                            .addComponent(jSenha)
                            .addComponent(jFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDepartamento))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jrMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jrFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jOBS)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jrMasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jOBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jExcluir)
                                    .addComponent(jConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrFeminino)
                        .addGap(203, 203, 203)))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCPF, jCelular, jDepartamento, jEmail, jNome, jOBS});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCadastrar, jEdit, jExcluir, jLimpar, jNovo});

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public String modoDep;

    public void ManipulaInterfaceDep() {
        switch (modoDep) {

            case "Novo":
                jCadastrar.setEnabled(true);
                jLimpar.setEnabled(true);
                jNome.setEnabled(true);
                jCPF.setEnabled(true);

                jDataNascimento.setEnabled(true);
                jDepartamento.setEnabled(true);
                jCelular.setEnabled(true);
                jEmail.setEnabled(true);
                jFuncao.setEnabled(true);

                jSalario.setEnabled(true);

                jrMasculino.setEnabled(true);
                jrFeminino.setEnabled(true);
                jNovo.setEnabled(false);
                jExcluir.setEnabled(false);

                jEdit.setEnabled(false);
                jOBS.setEnabled(true);
                break;

            case "Editar":
                jCadastrar.setEnabled(false);
                jLimpar.setEnabled(true);
                jNome.setEnabled(true);
                jCPF.setEnabled(true);

                jDataNascimento.setEnabled(true);
                jDepartamento.setEnabled(true);
                jCelular.setEnabled(true);
                jEmail.setEnabled(true);
                jFuncao.setEnabled(true);

                jSalario.setEnabled(true);

                jrMasculino.setEnabled(true);
                jrFeminino.setEnabled(true);
                jEdit.setEnabled(false);
                jNovo.setEnabled(false);

                jExcluir.setEnabled(false);

                jOBS.setEnabled(true);
                break;

            case "Excluir":
                jNovo.setEnabled(true);
                jCadastrar.setEnabled(false);
                jLimpar.setEnabled(false);

                jNome.setEnabled(false);
                jCPF.setEnabled(false);

                jDataNascimento.setEnabled(false);
                jDepartamento.setEnabled(false);
                jCelular.setEnabled(false);
                jEmail.setEnabled(false);
                jFuncao.setEnabled(false);
                jSalario.setEnabled(false);

                jrMasculino.setEnabled(false);
                jrFeminino.setEnabled(false);
                jExcluir.setEnabled(false);

                jEdit.setEnabled(false);
                jOBS.setEnabled(false);
                break;

            case "Selecao":
                jCadastrar.setEnabled(false);
                jLimpar.setEnabled(false);
                jNovo.setEnabled(true);
                jNome.setEnabled(false);
                jCPF.setEnabled(false);

                jDataNascimento.setEnabled(false);
                jDepartamento.setEnabled(false);
                jCelular.setEnabled(false);
                jEmail.setEnabled(false);
                jFuncao.setEnabled(false);

                jSalario.setEnabled(false);

                jrMasculino.setEnabled(false);
                jrFeminino.setEnabled(false);
                jExcluir.setEnabled(true);

                jEdit.setEnabled(true);
                jOBS.setEnabled(false);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Modo inválido");
        }
    }

    public void limpar() {
        jNome.setText("");
        jCPF.setText("");

        jDataNascimento.setText("");
        jDepartamento.setText("");
        jCelular.setText("");
        jEmail.setText("");
        ;
        jSalario.setText("");

        jOBS.setText("");
    }

    private void jNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoActionPerformed
        modoDep = "Novo";
        ManipulaInterfaceDep();
    }//GEN-LAST:event_jNovoActionPerformed

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        String sql = "SELECT * FROM funcionario WHERE CFP='"
                + jCPF.getText().replaceAll("[-,.]", "") + "'";
        BD.setResultSet(sql);
        String nom = "";
        try {
            BD.resultSet.next();
            nom = "Deletar o Funcionario:" + BD.resultSet.getString("Nome") + " CPF " + BD.resultSet.getString("CPFS");
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(null, "Funcionario não cadastrado!");
            jCPF.requestFocus();
            BD.setResultSet("SELECT * FROM funcionario");
            return;
        }
        int n = JOptionPane.showConfirmDialog(null, nom, "", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            sql = "DELETE FROM funconario WHERE CPF='" + jCPF.getText() + "'";
            int r = BD.runSQL(sql);
            if (r == 1) {
                JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o Funcionario!");

            }
        }
        BD.setResultSet("SELECT * FROM Funcionario");
    }//GEN-LAST:event_jExcluirActionPerformed

    private void jLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimparActionPerformed

    }//GEN-LAST:event_jLimparActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data = LocalDate.parse(jDataNascimento.getText(), formato);
        System.out.println(data);
        double Salario = Double.parseDouble(jSalario.getText());

        LocalDate data2 = LocalDate.parse(jDataEntrada.getText(), formato);
        System.out.println(data2);

        String sql = "";

        sql = "UPDATE funcionario SET "
                + "nome='" + jNome.getText() + "',"
                + "Email=" + jEmail.getText() + ","
                + "DataNascimento='" + data + "',"
                + "Salario='" + Salario + "',"
                + "Celular='" + jCelular.getText() + "',"
                + "DataEntrada=" + data2 + ","
                + "Departamenro=" + Funcao + ","
                + "Funcao=" + jDepartamento.getText() + ","
                + "Password=" + jSenha.getText() + ","
                + "OBS='" + jOBS.getText() + "',"
                + " WHERE CPF = " + jCPF.getText().replaceAll("[-,.]", "");
        System.out.println(sql);
        int r = BD.runSQL(sql);
        if (r == 1) {
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");

        } else {
            JOptionPane.showMessageDialog(null, "Problemas na Alteração, verifique se "
                    + "você digitou os campos corretamente!");
        }
        BD.setResultSet("SELECT * FROM produto");
    }//GEN-LAST:event_jEditActionPerformed

    private void jCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCPFActionPerformed

    private void jCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCelularActionPerformed

    private void jNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeActionPerformed


    private void jDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDepartamentoActionPerformed

    private void jCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarActionPerformed

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data = LocalDate.parse(jDataNascimento.getText(), formato);
        System.out.println(data);
        double Salario = Double.parseDouble(jSalario.getText());

        LocalDate data2 = LocalDate.parse(jDataEntrada.getText(), formato);
        System.out.println(data2);

        String sql = " INSERT INTO funcionario (Nome ,CPF, Email,DataNascimento,Sexo, Salario, Celular, DataEntrada, Departamento, Funcao, OBS, Password) Values ('"
                + jNome.getText() + "','"
                + jCPF.getText().replace(".", "").replace("-", "") + "','"
                + jEmail.getText() + "','"
                + data + "','"
                + Sexo + "',"
                + Salario + ",'"
                + jCelular.getText().replace("(", "").replace(")", "").replace("-", "") + "','"
                + data2 + "','"
                + jDepartamento.getText() + "','"
                + Funcao + "','"
                + jOBS.getText() + "','"
                + jSenha.getText() + "')";

        System.out.println(sql);
        int inserecliente = BD.runSQL(sql);
        if (inserecliente == 1) {
            JOptionPane.showMessageDialog(null, "Inclusão realizada com sucesso!");
            modoDep = "Cadastrar";
            ManipulaInterfaceDep();
            System.out.println(sql);
        } else {
            JOptionPane.showMessageDialog(null, "Problemas na Inclusão, verifique se "
                    + "você digitou os campos corretamente!");
        }
        BD.setResultSet("SELECT * FROM funcionario");

        modoDep = "Novo";
        ManipulaInterfaceDep();

    }//GEN-LAST:event_jCadastrarActionPerformed

    private void jrMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMasculinoActionPerformed
        Sexo = "M";
    }//GEN-LAST:event_jrMasculinoActionPerformed

    private void jFuncaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFuncaoFocusGained


    }//GEN-LAST:event_jFuncaoFocusGained

    private void jFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFuncaoActionPerformed
        if (jFuncao.getSelectedIndex() == 0) {
            Funcao = "Vendas";

        } else {
            if (jFuncao.getSelectedIndex() == 1) {
                Funcao = "GerenteC";
            } else {
                if (jFuncao.getSelectedIndex() == 2) {
                    Funcao = "GestorC";
                } else {
                    if (jFuncao.getSelectedIndex() == 3) {
                        Funcao = "Esped";
                    } else {
                        if (jFuncao.getSelectedIndex() == 4) {
                            Funcao = "Esped";
                        } else {
                            if (jFuncao.getSelectedIndex() == 5) {
                                Funcao = "Ti";
                            } else {
                                JOptionPane.showMessageDialog(null, "Opção selecionada Invalida");
                            }
                        }

                    }
                }
            }

        }

        System.out.println(jFuncao.getSelectedIndex());


    }//GEN-LAST:event_jFuncaoActionPerformed

    private void jConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarActionPerformed

    }//GEN-LAST:event_jConsultarActionPerformed

    private void jrFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFemininoActionPerformed
        Sexo = "F";
    }//GEN-LAST:event_jrFemininoActionPerformed
    private void setFocusLostBehavior() {
        int PERSIST = JFormattedTextField.PERSIST;
        jCPF.setFocusLostBehavior(PERSIST);
        jDataNascimento.setFocusLostBehavior(PERSIST);
        jDataEntrada.setFocusLostBehavior(PERSIST);
        jCelular.setFocusLostBehavior(PERSIST);
        jSalario.setFocusLostBehavior(PERSIST);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jCPF;
    private javax.swing.JButton jCadastrar;
    private javax.swing.JButton jCancelar;
    private javax.swing.JFormattedTextField jCelular;
    private javax.swing.JButton jConsultar;
    private javax.swing.JFormattedTextField jDataEntrada;
    private javax.swing.JFormattedTextField jDataNascimento;
    private javax.swing.JTextField jDepartamento;
    private javax.swing.JButton jEdit;
    private javax.swing.JTextField jEmail;
    private javax.swing.JButton jExcluir;
    private javax.swing.JComboBox<String> jFuncao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLimpar;
    private javax.swing.JTextField jNome;
    private javax.swing.JButton jNovo;
    private javax.swing.JTextField jOBS;
    private javax.swing.JFormattedTextField jSalario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSenha;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    // End of variables declaration//GEN-END:variables

}
