/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe Gai
 */
public class ProdutosView extends javax.swing.JFrame {
    //Gerador chama a class tabela e dá um nome

    public boolean aux = true;
    public static String escolha1 = "";
    DefaultTableModel dtm = new DefaultTableModel();
    String pesquisa = null;
    //.........................................
    private String ordem = "";

    public ProdutosView() {
        initComponents();
        // carregatabela();
        setLocationRelativeTo(null);
        dtm.addColumn("Descrição");
        dtm.addColumn("Codigo do produto");
        dtm.addColumn("Valor de Custo");
        dtm.addColumn("Valor de Venda");
        dtm.addColumn("Marca");
        dtm.addColumn("Grupo");
        dtm.addColumn("Unidade");
        dtm.addColumn("Quantidade");
        dtm.addColumn("Lucro");
        dtm.addColumn("Desconto");
        jTabela.setModel(dtm);
        carregatabela();

        if (!BD.getConnection()) {
            JOptionPane.showMessageDialog(null, "Falha na conexão, o sistema será fechado");
            System.exit(0);

        }

        BD.setResultSet("SELECT * FROM produto");

        setLocationRelativeTo(null);
        LoadTable();

        //RelativeNull é para a tela ficar centralizada
        setLocationRelativeTo(null);

        //Modo "Excluir" desativa a maioria dos botões
        //..........................................
    }
    public static int index;

    public void LoadTable() {
        if (aux == true) {
            //Modelo recebe a criação de tabelas

        } else {

        }
        //Seta o conteúdo de modelo na tabela local

        //.........................................
        //Define as larguras de cada posição
        jTabela.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTabela.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTabela.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTabela.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTabela.getColumnModel().getColumn(4).setPreferredWidth(30);
        jTabela.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTabela.getColumnModel().getColumn(6).setPreferredWidth(40);
        jTabela.getColumnModel().getColumn(7).setPreferredWidth(10);
        jTabela.getColumnModel().getColumn(8).setPreferredWidth(5);
        //..................................
    }
    int IDproduto = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jMarca = new javax.swing.JTextField();
        jDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jValorVenda = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jGrupo = new javax.swing.JTextField();
        jLucro = new javax.swing.JTextField();
        jDesconto = new javax.swing.JTextField();
        jCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jQuantidade = new javax.swing.JTextField();
        jValorCusto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jUnidade = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jExcluir = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jSalvar = new javax.swing.JButton();
        jLimpa = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jEscolha = new javax.swing.JComboBox<>();
        jPesquisar = new javax.swing.JButton();
        jLoad = new javax.swing.JButton();
        jOrdemCres = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setText("Cadastro de produtos");

        jTabela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Código do produto", "Valor de Custo", "Valor da venda", "Marca", "Descrição", "Grupo", "Lucro", "Desconto", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabelaMouseReleased(evt);
            }
        });
        jTabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabelaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTabela);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDescActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("VALOR DE CUSTO");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("MARCA");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("DESCRIÇÃO");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("VALOR DE VENDA");

        jValorVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorVendaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("GRUPO");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("LUCRO");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("DESCONTO");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("QUANTIDADE");

        jGrupo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLucroActionPerformed(evt);
            }
        });

        jDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDescontoActionPerformed(evt);
            }
        });

        jCod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("CODIGO");

        jQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Unidade");

        jUnidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jMarca, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jValorVenda, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCod)
                    .addComponent(jValorCusto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addComponent(jQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addComponent(jDesc)
                            .addComponent(jLucro)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesconto)
                            .addComponent(jUnidade))))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel9});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jValorCusto, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel6, jLabel9});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel13});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDesc, jMarca});

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(77, 77, 77))))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jExcluir.setText("Excluir");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });

        jbLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbLimpar.setText("Limpar campos");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSalvar.setText("Editar");
        jSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarActionPerformed(evt);
            }
        });

        jLimpa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLimpa.setText("Limpar linha");
        jLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpaActionPerformed(evt);
            }
        });

        jCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLimpa, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar)
                    .addComponent(jbNovo)
                    .addComponent(jLimpa)
                    .addComponent(jSalvar)
                    .addComponent(jExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jExcluir, jLimpa, jSalvar, jbCadastrar, jbLimpar, jbNovo});

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jEscolha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Descição", "Marca", "Grupo", "Valor de Custo", "Valor de Venda", "Quantidade", "Lucro" }));
        jEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEscolhaActionPerformed(evt);
            }
        });

        jPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPesquisar.setText("Pesquisar");
        jPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarActionPerformed(evt);
            }
        });

        jLoad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLoad.setText("Recarregar tabela");
        jLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoadActionPerformed(evt);
            }
        });

        buttonGroup1.add(jOrdemCres);
        jOrdemCres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jOrdemCres.setText("Ordem Cerscrescente");
        jOrdemCres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOrdemCresActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setText("Ordem Decrescente");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jOrdemCres)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLoad)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLoad)
                .addComponent(jPesquisar)
                .addComponent(jOrdemCres)
                .addComponent(jRadioButton2))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jEscolha, jLoad, jPesquisar});

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpaActionPerformed


    }//GEN-LAST:event_jLimpaActionPerformed

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        String sql = "SELECT * FROM produto WHERE codigo='"
                + jCod.getText() + "'";
        BD.setResultSet(sql);
        String nom = "";
        try {
            BD.resultSet.next();
            nom = "Deletar o Produto:" + BD.resultSet.getString("codigo");
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(null, "Produto não cadastrado!");
            jCod.requestFocus();
            BD.setResultSet("SELECT * FROM produto");
            return;
        }
        int n
                = JOptionPane.showConfirmDialog(null, nom, "", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            sql = "DELETE FROM produto WHERE codigo='" + jCod.getText() + "'";
            int r = BD.runSQL(sql);
            if (r == 1) {
                JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o Produto!");

            }
        }
        BD.setResultSet("SELECT * FROM produto");
    }//GEN-LAST:event_jExcluirActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        System.out.println(jQuantidade.getText());
        int quant = Integer.parseInt(jQuantidade.getText());
        System.out.println(quant);

        double ValorCusto = Double.parseDouble(jValorCusto.getText());
        double Lucro = Double.parseDouble(jLucro.getText());
        double Desconto = Double.parseDouble(jDesconto.getText());
        double ValorVenda = Double.parseDouble(jValorVenda.getText());

        String sql = " INSERT INTO produto (codigo ,descr, quantest,unidade, marca , grupo, valorcusto, lucro, desconto,  valorvenda ) Values ('"
                + jCod.getText() + "','"
                + jDesc.getText() + "',"
                + quant + ",'"
                + jUnidade.getText() + "','"
                + jMarca.getText() + "','"
                + jGrupo.getText() + "',"
                + ValorCusto + ","
                + Lucro + ","
                + Desconto + ","
                + ValorVenda + ")";

        System.out.println(sql);
        int inserecliente = BD.runSQL(sql);
        if (inserecliente == 1) {
            JOptionPane.showMessageDialog(null, "Inclusão realizada com sucesso!");
            modoDep = "Cadastrar";
            ManipulaInterfaceDep();
            System.out.println(sql);
        } else {
            JOptionPane.showMessageDialog(null, "Problemas na Inclusão, verifique se "
                    + "você digitou os campos corretamente!");
        }
        BD.setResultSet("SELECT * FROM produto");


    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limpar();
        modoDep = "Novo";
        ManipulaInterfaceDep();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarActionPerformed
        String sql = "";

        sql = " SELECT IDproduto FROM produto WHERE codigo ='"
                + jCod.getText() + "'";
        BD.setResultSet(sql);
        try {
            IDproduto = BD.resultSet.getInt("IDproduto");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Produto não encontrado!");
        }
        System.out.println(IDproduto);

        int quant = Integer.parseInt(jDesconto.getText());
        double ValorCusto = Double.parseDouble(jValorCusto.getText());
        double Lucro = Double.parseDouble(jLucro.getText());
        double Desconto = Double.parseDouble(jQuantidade.getText());
        double ValorVenda = Double.parseDouble(jValorVenda.getText());

        sql = "UPDATE produto SET "
                + "codigo='" + jCod.getText() + "',"
                + "descr='" + jDesc.getText() + "',"
                + "quantest=" + quant + ","
                + "unidade='" + jUnidade.getText() + "',"
                + "marca='" + jMarca.getText() + "',"
                + "grupo='" + jGrupo.getText() + "',"
                + "valorcusto=" + ValorCusto + ","
                + "lucro=" + Lucro + ","
                + "desconto=" + Desconto + ","
                + "valorvenda=" + ValorVenda + ","
                + "OBS='" + jDesc.getText() + "',"
                + " WHERE IDproduto = " + IDproduto;
        System.out.println(sql);

        int r = BD.runSQL(sql);
        if (r == 1) {
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");

        } else {
            JOptionPane.showMessageDialog(null, "Problemas na Alteração, verifique se "
                    + "você digitou os campos corretamente!");
        }
        BD.setResultSet("SELECT * FROM produto");


    }//GEN-LAST:event_jSalvarActionPerformed

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
        int row = jTabela.getSelectedColumn();
        jDesc.setText((String) dtm.getValueAt(row, 0));
        jCod.setText((String) dtm.getValueAt(row, 1));
        jValorCusto.setText((String) dtm.getValueAt(row, 2));
        jValorVenda.setText((String) dtm.getValueAt(row, 3));
        jMarca.setText((String) dtm.getValueAt(row, 4));
        jGrupo.setText((String) dtm.getValueAt(row, 5));
        jUnidade.setText((String) dtm.getValueAt(row, 6));
        jQuantidade.setText((String) dtm.getValueAt(row, 7));
        jLucro.setText((String) dtm.getValueAt(row, 8));
        jDesconto.setText((String) dtm.getValueAt(row, 9));

    }//GEN-LAST:event_jTabelaMouseClicked

    private void jPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarActionPerformed
        String sql;
        pesquisa = null;

        switch (jEscolha.getSelectedIndex()) {
            case 0:
                pesquisa = "codigo";
                break;
            case 1:
                pesquisa = "descr";
                break;
            case 2:
                pesquisa = "marca";
                break;

            case 3:
                pesquisa = "grupo";
                break;

            case 4:
                pesquisa = "valorcusto";
                break;

            case 5:
                pesquisa = "valorvenda";
                break;

            case 6:
                pesquisa = "quantest";
                break;

            case 7:
                pesquisa = "lucro";
                break;

            default:
                JOptionPane.showMessageDialog(null, "Selecione o criterio de Pesquisa");

        }
        System.out.println(jEscolha.getSelectedIndex());
        int rowCount = dtm.getRowCount();
        //Remove rows one by one from the end of the table
        if (rowCount != 0) {
            for (int a = rowCount; a >= 0; a--) {
                dtm.removeRow(a - 1);

            }
        }

        //System.out.println(jEscolha.getSelectedItem());
        sql = "SELECT * FROM produto ORDER BY " + "'" + pesquisa + "'" + ordem;
        System.out.println(sql);
        BD.setResultSet(sql);

        try {
            while (BD.resultSet.next()) {

                String codigo = BD.resultSet.getNString("codigo");
                String descr = BD.resultSet.getString("descr");
                String quant = BD.resultSet.getString("quantest");
                String unidade = BD.resultSet.getString("unidade");
                String grupo = BD.resultSet.getString("grupo");
                String marca = BD.resultSet.getString("marca");
                String valorcusto = BD.resultSet.getString("valorcusto");
                String lucro = BD.resultSet.getString("lucro");
                String desconto = BD.resultSet.getString("desconto");
                String valorvenda = BD.resultSet.getString("valorvenda");

                dtm.addRow(new String[]{descr, codigo, valorcusto, valorvenda, marca, grupo, unidade, quant, lucro, desconto});

            }
        } catch (SQLException ex) {
            Logger.getLogger(ProdutosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPesquisarActionPerformed

    private void jLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoadActionPerformed
        int rowCount = dtm.getRowCount();
        //Remove rows one by one from the end of the table
        if (rowCount != 0) {
            for (int a = rowCount; a >= 0; a--) {
                dtm.removeRow(a - 1);

            }
        }

        carregatabela();

    }//GEN-LAST:event_jLoadActionPerformed

    private void jDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDescontoActionPerformed

    private void jTabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaKeyReleased
        eventTable();
    }//GEN-LAST:event_jTabelaKeyReleased

    private void jTabelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseReleased
        eventTable();
    }//GEN-LAST:event_jTabelaMouseReleased

    private void jEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEscolhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEscolhaActionPerformed

    private void jLucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLucroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLucroActionPerformed

    private void jValorVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorVendaActionPerformed

    private void jDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDescActionPerformed

    private void jOrdemCresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOrdemCresActionPerformed
        ordem = "";
    }//GEN-LAST:event_jOrdemCresActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       ordem = " desc";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    public void ManipulaInterfaceDep() {

        switch (modoDep) {

            case "Novo":
                jbCadastrar.setEnabled(true);
                jbLimpar.setEnabled(true);
                jLimpa.setEnabled(false);

                jLoad.setEnabled(false);
                jPesquisar.setEnabled(false);
              
                jEscolha.setEnabled(false);
                jDesc.setEnabled(false);

                jCod.setEnabled(true);
                jDesconto.setEnabled(true);

                jValorCusto.setEnabled(true);
                jMarca.setEnabled(true);

                jValorVenda.setEnabled(true);
                jGrupo.setEnabled(true);
                jDesc.setEnabled(true);

                jLucro.setEnabled(true);

                jbNovo.setEnabled(false);

                jSalvar.setEnabled(false);
                jExcluir.setEnabled(false);

                break;

            case "Editar":
                jbCadastrar.setEnabled(false);
                jbLimpar.setEnabled(true);

                jLoad.setEnabled(false);
                jPesquisar.setEnabled(false);
               
                jEscolha.setEnabled(false);
                jDesc.setEnabled(false);

                jCod.setEnabled(true);
                jDesconto.setEnabled(true);

                jValorCusto.setEnabled(true);
                jMarca.setEnabled(true);

                jValorVenda.setEnabled(true);
                jGrupo.setEnabled(true);
                jDesc.setEnabled(true);

                jLucro.setEnabled(true);

                jExcluir.setEnabled(false);
                jbNovo.setEnabled(false);
                jLimpa.setEnabled(false);

                jSalvar.setEnabled(true);

                break;

            case "Excluir":
                jbNovo.setEnabled(true);
                jbCadastrar.setEnabled(false);
                jbLimpar.setEnabled(false);
                jLimpa.setEnabled(false);
                jDesc.setEnabled(false);

                jCod.setEnabled(false);
                jDesconto.setEnabled(false);

                jValorCusto.setEnabled(false);
                jMarca.setEnabled(false);

                jValorVenda.setEnabled(false);
                jGrupo.setEnabled(false);
                jDesc.setEnabled(false);

                jLucro.setEnabled(false);

                jSalvar.setEnabled(false);
                jExcluir.setEnabled(false);

                break;

            case "Selecao":
                jbCadastrar.setEnabled(false);
                jbLimpar.setEnabled(false);
                jbNovo.setEnabled(true);
                jDesc.setEnabled(false);
                jCod.setEnabled(false);
                jDesconto.setEnabled(false);

                jValorCusto.setEnabled(false);
                jMarca.setEnabled(false);

                jValorVenda.setEnabled(false);
                jGrupo.setEnabled(false);
                jDesc.setEnabled(false);

                jLucro.setEnabled(false);

                jSalvar.setEnabled(false);
                jLimpa.setEnabled(true);
                jExcluir.setEnabled(true);

                jLoad.setEnabled(true);
                jPesquisar.setEnabled(true);
                
                jEscolha.setEnabled(true);
                break;

            default:
                JOptionPane.showMessageDialog(null, "Modo inválido");
        }
    }

    public void carregatabela() {

        String sql = "SELECT * FROM produto";
        BD.setResultSet(sql);

        try {
            while (BD.resultSet.next()) {

                String codigo = BD.resultSet.getNString("codigo");
                String descr = BD.resultSet.getString("descr");
                String quant = BD.resultSet.getString("quantest");
                String unidade = BD.resultSet.getString("unidade");
                String grupo = BD.resultSet.getString("grupo");
                String marca = BD.resultSet.getString("marca");
                String valorcusto = BD.resultSet.getString("valorcusto");
                String lucro = BD.resultSet.getString("lucro");
                String desconto = BD.resultSet.getString("desconto");
                String valorvenda = BD.resultSet.getString("valorvenda");

                dtm.addRow(new String[]{descr, codigo, valorcusto, valorvenda, marca, grupo, unidade, quant, lucro, desconto});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProdutosView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ProdutosView().setVisible(true);
            }
        });
    }

    public void limpar() {
        jDesc.setText("");
        jDesconto.setText("");
        jValorCusto.setText("");
        jMarca.setText("");

        jValorVenda.setText("");
        jGrupo.setText("");
        jDesc.setText("");

        jLucro.setText("");
    }

    public String modoDep;

    public Color BackGround = Color.CYAN;

    public void eventTable() {

        if (BackGround != Color.ORANGE && BackGround != Color.CYAN) {
            jTabela.setSelectionBackground(BackGround);
        } else {
            BackGround = jTabela.getSelectionBackground();
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jCancelar;
    private javax.swing.JTextField jCod;
    private javax.swing.JTextField jDesc;
    private javax.swing.JTextField jDesconto;
    private javax.swing.JComboBox<String> jEscolha;
    private javax.swing.JButton jExcluir;
    private javax.swing.JTextField jGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLimpa;
    private javax.swing.JButton jLoad;
    private javax.swing.JTextField jLucro;
    private javax.swing.JTextField jMarca;
    private javax.swing.JRadioButton jOrdemCres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jPesquisar;
    private javax.swing.JTextField jQuantidade;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton jSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JTextField jUnidade;
    private javax.swing.JTextField jValorCusto;
    private javax.swing.JTextField jValorVenda;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    // End of variables declaration//GEN-END:variables
}
